version: "3"
services:
  mongodb:
    image: mongodb
    container_name: fsaycondev-mongodb
    build:
      context: .
      dockerfile: mongo.Dockerfile
    restart: always
    volumes:
      - mongodb-vol:/data/db
    env_file:
      - mongo.env
  graphql-server:
    image: graphql-server
    container_name: fsaycondev-express-boilerplate
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./src:/app/src
    env_file:
      - server.env
volumes:
  mongodb-vol:
